name: Build

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout Latest
        uses: actions/checkout@v3
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - name: Zig Build Project
        run: zig build
      - name: Zig Build Example
        run: zig build run