name: Docs

on:
  - push

permissions:
  contents: write

jobs:
  docs:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest
        uses: actions/checkout@v3

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
        
      - name: Zig Build Project
        run: zig build docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: zig-out/docs/
